# Generated by Django 4.1.1 on 2022-10-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_extra_horse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='extra_horse',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
