# Generated by Django 4.1.1 on 2022-10-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_extra_horse'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=4),
        ),
    ]
