# Generated by Django 4.1.1 on 2023-01-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=4, null=True),
        ),
    ]
